# Generated by Django 4.2.20 on 2026-05-20 15:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='RetailPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('point_type', models.CharField(choices=[('head', 'Головной отдел'), ('dealer', 'Дилерский центр')], default='dealer', verbose_name='Тип точки')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=20, verbose_name='Номер дома')),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Выручка за день')),
            ],
            options={
                'verbose_name': 'Торговая точка',
                'verbose_name_plural': 'Торговые точки',
            },
        ),
        migrations.AddConstraint(
            model_name='retailpoint',
            constraint=models.UniqueConstraint(condition=models.Q(('point_type', 'head')), fields=('point_type',), name='only_one_head_office'),
        ),
        migrations.AddField(
            model_name='employee',
            name='retail_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='retail.retailpoint', verbose_name='Торговая точка'),
        ),
    ]
