# Generated by Django 4.2.20 on 2026-05-21 01:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, null=True, editable=False, verbose_name='API-ключ'),
        ),
    ]
