# Generated by Django 4.2.20 on 2026-05-21 01:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0003_employee_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.AlterField(
            model_name='employee',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='API-ключ'),
        ),
    ]
