# Generated by Django 4.2.20 on 2026-05-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retail', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='retail_point',
            field=models.ForeignKey(limit_choices_to={'point_type': 'dealer'}, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='retail.retailpoint', verbose_name='Торговая точка'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('product', 'retail_point'), name='unique_product_per_dealer'),
        ),
    ]
